exports.workouts = [
    {title: 'Hip Thrust', description: 'Place your back on an exercise ball or bench and your glutes on the floor. Place one weight horizontally across the hips. You can also place one weight on each hip. Perform a hip thrust by squeezing the glutes and pressing the dumbbell straight up until the hips align with the shoulders and knees.' },
    {title: 'Barbell Squat', description: 'Perform barbell squats by standing with your feet shoulder-width apart. Take a deep breath and unrack a weighted barbell, holding it on your upper back. Keep your chest up and your back straight as you hinge your hips and knees to lower your body through a full range of motion into a squat position.'},
    {title: 'Reverse lounges', description: 'With a reverse lunge, you will be stepping backward with one of your legs. You bend your back leg so your back knee will nearly touch the ground, and your front knee so your thigh is about parallel to the ground. Your front, planted leg is the one that will be working.'},
    {title: 'Dead Lift', description: 'The deadlift is a movement in which your hips hinge backward to lower down and pick up a weighted barbell or kettlebell from the floor. Your back is flat throughout the movement. Some benefits of performing deadlifts include strengthening and gaining more definition in your upper and lower back, glutes, and hamstrings.'},
    {title: 'Leg press', description: 'Leg presses are seated exercises done on a leg press machine. To start, sit with your back against a padded backrest and your feet on two large footrests. Your knees are bent to start the exercise. To move the weight, you must straighten your legs and then return them to the bent position.'},
    {title: 'Lat Pulldown', description: 'The lat pulldown is an exercise where you sit at a machine with a bar overhead. You pull the bar down towards your chest, engaging your back muscles. Then, you slowly release the bar back to the starting position. It primarily works the muscles of the back, especially the latissimus dorsi. Focus on good form and controlled movements to get the most benefit and prevent injury.'},
    {title: 'Cable Rows', description: 'Cable rows are a strength training exercise performed on a cable machine. Stand in front of the machine, grab the handle, and pull it towards your body, squeezing your shoulder blades together. Slowly return to the starting position. Cable rows target the upper back muscles and improve posture and strength.'},
    {title: 'One-Arm Dumbble Row', description: 'The one-arm dumbbell row is a strength exercise where you bend forward, brace one hand and one knee on a bench, and lift a dumbbell with the opposite hand, pulling it towards your hip while keeping your back straight. This exercise primarily targets the muscles of the back, including the lats and rhomboids, as well as the biceps. It is effective for building unilateral strength and addressing muscle imbalances.'},
    {title: 'Hammer Curls', description: 'Hammer curls are a biceps exercise where you stand with dumbbells in each hand, palms facing each other. You curl the weights towards your shoulders while keeping your elbows close to your body. This targets the biceps and forearms. Lower the weights back down in a controlled manner. It is a simple yet effective exercise for building arm strength and muscle definition.'},
    {title: 'Dumbbell Shoulder Press', description: 'The dumbbell shoulder press is a fundamental exercise for developing shoulder strength and muscle mass. To perform it, sit or stand with a dumbbell in each hand at shoulder height, palms facing forward. Press the weights upward until your arms are fully extended, then lower them back down to shoulder level. Keep your core engaged and avoid arching your back. The dumbbell shoulder press primarily targets the deltoid muscles of the shoulders, with additional engagement from the triceps and upper chest. '},
    {title: 'Lateral Raises', description: 'Lateral raises are a shoulder-strengthening exercise. To perform them, stand with dumbbells at your sides. With a slight bend in your elbows, lift the weights outward until they reach shoulder level. Maintain control and avoid swinging the weights. Lower the dumbbells back down and repeat. Lateral raises primarily target the lateral deltoids, helping to build broader shoulders.'},
    {title: 'Triceps Pushdown-Ropes', description: 'Triceps pushdown with ropes is a popular strength-training exercise that targets the triceps muscles. To perform it, stand facing a cable machine with a rope attachment set at the top pulley. Grasp the rope ends with an overhand grip, keeping your elbows close to your sides and your forearms parallel to the ground. Push the rope downward by straightening your arms until they are fully extended, then return to the starting position by controlling the weights ascent. Focus on squeezing your triceps at the bottom of the movement.'},
    {title: 'Overhead Triceps Extension', description: 'The overhead triceps extension is a strength-building exercise that primarily targets the triceps muscles. To perform it, stand or sit with a dumbbell or a weight plate held overhead with both hands. Keep your elbows close to your head and lower the weight behind your head by bending your elbows. Extend your arms to raise the weight back up, fully straightening your elbows. Maintain control throughout the movement, and avoid locking out your elbows at the top.'},
    {title: 'Step-Ups', description: 'Step-ups are a lower body exercise that primarily targets the quadriceps, hamstrings, glutes, and calves. To perform step-ups, stand in front of a sturdy bench or platform. Step onto the bench with one foot, driving through the heel to lift your body up until the front leg is straight. Then, lower yourself back down under control. Alternate legs for each repetition. Step-ups are effective for building lower body strength, improving balance, and enhancing overall leg development.'},
    {title: 'Push-Ups', description: 'Push-ups are bodyweight exercises targeting chest, shoulders, triceps, and core. Start in a plank position, hands shoulder-width apart. Lower your body until your chest almost touches the ground, then push back up. Keep your body straight throughout. Modify by doing on knees or elevating hands.'},
    {title: 'Bent-Over Rows', description: 'Bent-over rows are a compound exercise targeting the upper back, lats, and biceps. Hold a dumbbell in each hand, hinge at the hips, and keep your back straight. Pull the weights towards your torso, squeezing your shoulder blades together, then lower back down. '},
    {title: 'Plank', description: 'The plank is a core-strengthening exercise that also engages the shoulders, chest, and back. Begin in a push-up position with your hands directly beneath your shoulders and your body forming a straight line from head to heels. Engage your core muscles, keep your back flat, and hold this position for a set amount of time.'}
  ];